### ISSUE TITLE
op mobiel gaat de bar over de tekst heen

### ISSUE THREAD

**Issue by yujing-student** [lisagjh/profile-card-SPR13#8]
![image](https://github.com/user-attachments/assets/75344bc4-7484-4853-b7c3-2224d77aab2f)

misschien zou je dit met grid kunnen oplossen dat je grid-rows gebruikt en dat je geen overlapping kan hebben

**Comment by yujing-student** [comment]
<h1>w3c validator</h1>

![image](https://github.com/user-attachments/assets/65955ac2-0af3-499f-a490-0a46dbd86931)

uit de webdeveloper tool kwam dit toen ik de html aan het valideren was

<h1>een compliment je hebt goed gelet op toegankelijkheid</h1>
en een compliment vanwege toegankelijkheid
![image](https://github.com/user-attachments/assets/c0a6f103-1cf9-4379-8310-e6bc865c0a1e)

<h1>let op naamgeving</h1>
naamgeving wat is var(--w)
![image](https://github.com/user-attachments/assets/2a39c367-8f65-4083-898e-95aa83b02418)

wat is var(--i)
![image](https://github.com/user-attachments/assets/a2a12b2e-b5b6-49f4-96ed-2e7a055addb1)

**Comment by lisagjh** [comment]
### tekst en bar overlap op mobiel

heb de negatieve margin van de h3 verwijdert, waardoor dit nu niet meer gebeurt.

![IMG_5553](https://github.com/user-attachments/assets/5b4d4b66-f04b-4452-8471-d835a4c05db6)

### validator: alt op src

ik heb de alts weg gehaald #:+1: 

### toegankelijkheid

dank je wel :)

### naamgeving

ik heb bij de --w en --i een comment gezet waar het voor is, om het zo duidelijker te maken.

**Comment by Yu-Jing-van-Gerwen** [comment]
ziet er echt goed uit
